export const DonateInfo = [
  {
    title: "Empower her",
    rupees: "rs.2000/month",
    img: "",
    subtitle: "Sponser a girl child",
    points: [
      "Medical care",
      "Educational support",
      "Health and Nutrition",
      "Personal mentorship",
      "Hygene and Sanitation",
      "Imparting ethics and values and more",
    ],
    bg_color: "emerald-600",
    class: "emerald",
  },
  {
    title: "Empower her",
    rupees: "rs.2000/month",
    img: "",
    subtitle: "Sponser a girl child",
    points: [
      "Medical care",
      "Educational support",
      "Health and Nutrition",
      "Personal mentorship",
      "Hygene and Sanitation",
      "Imparting ethics and values and more",
    ],
    bg_color: "zinc-600",
    class: "zinc",
  },
  {
    title: "Empower her",
    rupees: "rs.2000/month",
    img: "",
    subtitle: "Sponser a girl child",
    points: [
      "Medical care",
      "Educational support",
      "Health and Nutrition",
      "Personal mentorship",
      "Hygene and Sanitation",
      "Imparting ethics and values and more",
    ],
    bg_color: "red-800",
    class: "red",
  },
  {
    title: "Empower her",
    rupees: "rs.2000/month",
    img: "",
    subtitle: "Sponser a girl child",
    points: [
      "Medical care",
      "Educational support",
      "Health and Nutrition",
      "Personal mentorship",
      "Hygene and Sanitation",
      "Imparting ethics and values and more",
    ],
    bg_color: "blue-600",
    class: "blue",
  },
  {
    title: "Empower her",
    rupees: "rs.2000/month",
    img: "",
    subtitle: "Sponser a girl child",
    points: [
      "Medical care",
      "Educational support",
      "Health and Nutrition",
      "Personal mentorship",
      "Hygene and Sanitation",
      "Imparting ethics and values and more",
    ],
    bg_color: "zinc-600",
    class: "gray",
  },
];
